project:
  type: website

website:
  title: "My Data Stories"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sphiawang
format:
  html:
    theme: minty
    css: styles.css

execute:
  freeze: auto


